layui.use(['layer','element'],function(){
    var layer = layui.layer
        ,element = layui.element;
    $(function(){
        $("#home_title").css("top",($(window).height()-$("#home_title").height())/2);
        $("#home_title").css("left",($(window).width()-$("#home_title").width())/2);
        $(window).resize(function(){
            $("#home_title").css("top",($(window).height()-$("#home_title").height())/2);
            $("#home_title").css("left",($(window).width()-$("#home_title").width())/2);
        });
        $("#link_home").click(function(){
            layer.msg($("#link_home").text());
            $("#bgdiv").fadeIn();
            $(".layui-nav").removeClass("layui-bg-black");
            $(".layui-nav").addClass("layui-bg-clean");
            $(".layui-header").removeClass("layui-bg-black");
            $(".layui-header").addClass("layui-bg-clean");
            $("#li_more").removeClass("layui-this");
            $("#li_about").removeClass("layui-this");
            $("#li_home").addClass("layui-this");
            $("#page_time").hide();
            $("#page_history").hide();
            $("#page_about").hide();
            $("#page_home").show();
            $("#home_title").css("top",($(window).height()-$("#home_title").height())/2);
            $("#home_title").css("left",($(window).width()-$("#home_title").width())/2);
            $("body").css("background-color","#000000");
        });
        $("#link_time").click(function(){
            layer.msg($("#link_time").text());
            $("#bgdiv").fadeOut();
            $(".layui-nav").addClass("layui-bg-black");
            $(".layui-nav").removeClass("layui-bg-clean");
            $(".layui-header").addClass("layui-bg-black");
            $(".layui-header").removeClass("layui-bg-clean");
            $("#li_home").removeClass("layui-this");
            $("#li_about").removeClass("layui-this");
            $("#li_more").addClass("layui-this");
            $("#page_home").hide();
            $("#page_history").hide();
            $("#page_about").hide();
            $("#page_time").show();
            $("body").css("background-color","#FFFFFF");
        });
        $("#link_history").click(function(){
            layer.msg($("#link_history").text());
            $("#bgdiv").fadeOut();
            $(".layui-nav").addClass("layui-bg-black");
            $(".layui-nav").removeClass("layui-bg-clean");
            $(".layui-header").addClass("layui-bg-black");
            $(".layui-header").removeClass("layui-bg-clean");
            $("#li_home").removeClass("layui-this");
            $("#li_about").removeClass("layui-this");
            $("#li_more").addClass("layui-this");
            $("#page_home").hide();
            $("#page_time").hide();
            $("#page_about").hide();
            $("#page_history").show();
            $("body").css("background-color","#FFFFFF");
        });
        $("#link_about").click(function(){
            layer.msg($("#link_about").text());
            $("#bgdiv").fadeOut();
            $(".layui-nav").addClass("layui-bg-black");
            $(".layui-nav").removeClass("layui-bg-clean");
            $(".layui-header").addClass("layui-bg-black");
            $(".layui-header").removeClass("layui-bg-clean");
            $("#li_home").removeClass("layui-this");
            $("#li_more").removeClass("layui-this");
            $("#li_about").addClass("layui-this");
            $("#page_home").hide();
            $("#page_time").hide();
            $("#page_history").hide();
            $("#page_about").show();
            $("body").css("background-color","#FFFFFF");
        });
    });
});
